server:
  port: ${EWM_SERVER_PORT}

ewm-server:
  url: ${EWM_SERVER_URL}

time:
  editing:

spring:
    jpa:
      properties:
        hibernate:
          dialect: org.hibernate.dialect.PostgreSQL10Dialect
          format_sql: true

    sql:
      init:
        mode: always

    datasource:
      driver-class-name: org.postgresql.Driver
      url: jdbc:postgresql://${DB_HOST}:${DB_PORT}/${DB_NAME}
      username: ${POSTGRES_USER}
      password: ${POSTGRES_PASSWORD}
