spring:
    jpa:
      properties:
        hibernate:
          dialect: org.hibernate.dialect.PostgreSQL10Dialect
          format_sql: true

    sql:
      init:
        mode: always

    datasource:
      driver-class-name: org.postgresql.Driver
      url: jdbc:postgresql://localhost:5432/postgres
      username: postgres
      password: postgres

#  server:
#    port: ${EWM_SERVER_PORT}
#
#  stats-server:
#    url: ${EWM_SERVER_URL}

#  jpa:
#    properties:
#      hibernate:
#        dialect: org.hibernate.dialect.PostgreSQL10Dialect
#        format_sql: true
#  sql:
#    init:
#      mode: always

#  datasource:
#    driver-class-name: org.postgresql.Driver
#    url: jdbc:postgresql://${DB_HOST}:${DB_PORT}/${DB_NAME}
#    username: ${POSTGRES_USER}
#    password: ${POSTGRES_PASSWORD}

server:
  port: 8080

#stats-server:
#  url: http://stats-client:9090


stats-server:
  url: http://localhost:9090
