version: '3.1'
services:
  stats-server-client:
    build: stats-server/client/
    image: stats-client-image
    container_name: stats-client
    ports:
      - "9090:9090"
    depends_on:
      - stats-server
    environment:
      - STATS_SERVER_URL=http://stats-server-service:9091

  stats-server:
    build: stats-server/service
    image: stats-service-image
    container_name: stats-service
    ports:
      - "9091:9091"
    depends_on:
      - stats-db
    environment:
      - DB_NAME=stats
      - POSTGRES_USER=root
      - POSTGRES_PASSWORD=root
      - DB_HOST=stats-db
      - DB_PORT=5432


  stats-db:
    image: postgres:14-alpine
    volumes:
      - /var/lib/postgresql/data/
    ports:
      - "6541:5432"
    environment:
      - POSTGRES_DB=stats
      - POSTGRES_USER=root
      - POSTGRES_PASSWORD=root

  ewm-service:
    build: ewm-service
    image: ewm-service-image
    container_name: ewm-service
    ports:
      - "8080:8080"

  ewm-db:
    image: postgres:14-alpine