version: '3.1'
services:
  stats-server-client:
    build: stats-server/client
    image: stats-client-image
    container_name: stats-client
    ports:
      - "9091:9091"
    depends_on:
      - stats-server
    environment:
      - STATS_SERVER_PORT=9091
      - STATS_SERVER_URL=http://stats-service:9090

  stats-server:
    build: stats-server/service
    image: stats-service-image
    container_name: stats-service
    ports:
      - "9090:9090"
    depends_on:
      - stats-db
    environment:
      - DB_NAME=stats
      - POSTGRES_USER=root
      - POSTGRES_PASSWORD=root
      - DB_HOST=stats-db
      - DB_PORT=5432
      - STATS_SERVER_PORT=9090

  stats-db:
    image: postgres:14-alpine
    volumes:
      - /var/lib/postgresql/data/
    ports:
      - "6541:5432"
    environment:
      - POSTGRES_DB=stats
      - POSTGRES_USER=root
      - POSTGRES_PASSWORD=root

  ewm-service:
    build: ewm-service
    image: ewm-service-image
    container_name: ewm-service
    ports:
      - "8080:8080"
    depends_on:
      - ewm-db
      - stats-server-client
    environment:
      - DB_NAME=ewm
      - POSTGRES_USER=root
      - POSTGRES_PASSWORD=root
      - DB_HOST=ewm-db
      - DB_PORT=5432
      - EWM_SERVER_PORT=8080
      - EWM_SERVER_URL=http://stats-client:9091

  ewm-db:
    image: postgres:14-alpine
    volumes:
      - /var/lib/postgresql/data/
    ports:
      - "6542:5432"
    environment:
      - POSTGRES_DB=ewm
      - POSTGRES_USER=root
      - POSTGRES_PASSWORD=root